<?php

namespace Proxies\__CG__\CMS\Model;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Site extends \CMS\Model\Site implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getHost()
    {
        $this->__load();
        return parent::getHost();
    }

    public function setHost($host)
    {
        $this->__load();
        return parent::setHost($host);
    }

    public function getTheme()
    {
        $this->__load();
        return parent::getTheme();
    }

    public function setTheme($theme)
    {
        $this->__load();
        return parent::setTheme($theme);
    }

    public function isActive()
    {
        $this->__load();
        return parent::isActive();
    }

    public function setActive()
    {
        $this->__load();
        return parent::setActive();
    }

    public function setInactive()
    {
        $this->__load();
        return parent::setInactive();
    }

    public function isMaintaining()
    {
        $this->__load();
        return parent::isMaintaining();
    }

    public function setMaintaining($maintaining = true)
    {
        $this->__load();
        return parent::setMaintaining($maintaining);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getPages()
    {
        $this->__load();
        return parent::getPages();
    }

    public function getKeywords()
    {
        $this->__load();
        return parent::getKeywords();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'host', 'theme', 'active', 'maintaining', 'description', 'pages', 'keywords');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}